spring:
  application:
    name: "sistema-votacoes"
  main:
    banner-mode: "off"

  datasource:
    url: jdbc:postgresql://localhost:5432/votacoes
    username: votacao
    password: votacao123
    driver-class-name: org.postgresql.Driver
    validationQuery: SELECT 1

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

  jackson:
    default-property-inclusion: non_null
    serialization:
      write_dates_as_timestamps: false

  kafka:
    bootstrap-servers: localhost:9092

    producer:
      aks: all
      compression-type: gzip
      retries: 3
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.exemplo.votacoes.configuracoes.kafka.JsonSerializerWithJTM
      properties.spring.json.add.type.headers: false

management:
  metrics:
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      base-path: /management
      exposure:
        include: health, info, prometheus
  endpoint:
    health:
      enabled: true
    info:
      enabled: true
    prometheus:
      enabled: true
  health:
    diskspace:
      enabled: false

logging:
  level:
    liquibase:
      executor: off

associado:
  url: https://user-info.herokuapp.com

openapi:
  titulo: API para gerenciar votações
  descricao: O serviço expoem endpoints para criação de votações, para iniciar sessões de votação, receber os votos dos associados e contabilizar o resultado.
  versao: 1

springdoc:
  swagger-ui:
    path: /swagger-ui.html

topicos:
  votacoes:
    nome: votacoes
    particoes: 3
    replicas: 1
  votos:
    nome: votos
    particoes: 3
    replicas: 1
